vince_t_admin_configuration_homepage:
    pattern:  /admin/configuration
    defaults: { _controller: VinceTAdminConfigurationBundle:Configuration:index }

vince_t_admin_configuration_group:
    pattern:  /admin/configuration/section/{sname}/group/{id}/{gname}
    defaults: { _controller: VinceTAdminConfigurationBundle:Configuration:group }
    requirements: 
        id: \d+

vince_t_admin_configuration_save:
    pattern: /admin/configuration/save/{id}
    defaults: { _controller: VinceTAdminConfigurationBundle:Configuration:save }
    requirements:
        methods: 'POST'