parameters:
#    vince_t_admin_configuration.example.class: VinceT\AdminConfigurationBundle\Example

services:
#    vince_t_admin_configuration.example:
#        class: %vince_t_admin_configuration.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
