parameters:
    admin.configuration.twig.extension.class: VinceT\AdminConfigurationBundle\Twig\Extension\AdminConfigurationExtension
    admin.configuration.manager.class: VinceT\AdminConfigurationBundle\Manager\AdminConfigurationManager
    admin.configuration.configtype_manager.class: VinceT\AdminConfigurationBundle\Manager\ConfigTypeManager
    admin.configuration.configvalue_manager.class: VinceT\AdminConfigurationBundle\Manager\ConfigValueManager
    admin.configuration.configgroup_manager.class: VinceT\AdminConfigurationBundle\Manager\ConfigGroupManager
    admin.configuration.configsection_manager.class: VinceT\AdminConfigurationBundle\Manager\ConfigSectionManager
    admin.configuration.configbuilder.class: VinceT\AdminConfigurationBundle\Configuration\AdminConfigurationBuilder
    admin.configuration.pool.class: VinceT\AdminConfigurationBundle\Configuration\Pool
services:
    admin.configuration.twig.extension:
        class: %admin.configuration.twig.extension.class%
        arguments:
            - @service_container
        tags:
            - { name: twig.extension }

    kernel.listener.admin_configuration_menu_listener:
        class: VinceT\AdminConfigurationBundle\EventListener\AdminMenuListener
        tags:
            - { name: kernel.event_listener, event: admin.menu.create, method: createMenu }

    admin.configuration.manager:
        class: '%admin.configuration.manager.class%'
        arguments:
            - '@service_container'

    admin.configuration.configsection_manager:
        class: '%admin.configuration.configsection_manager.class%'
        arguments:
            - '@service_container'
    admin.configuration.admin.configsection:
        class: VinceT\AdminConfigurationBundle\Admin\ConfigSectionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: AdminConfiguration, label: ConfigSection, label_translator_strategy: sonata.admin.label.strategy.underscore }
        arguments:
            - null
            - VinceT\AdminConfigurationBundle\Entity\ConfigSection
            - 'VinceTAdminConfigurationBundle:Admin/ConfigSectionAdmin'
        calls:
            - [setTranslationDomain, [VinceTAdminConfigurationBundleConfigSection]]
            - [setModelManager, ['@admin.configuration.configsection_manager']]
            - [setTemplate, [list, 'VinceTAdminConfigurationBundle:Configuration:list.html.twig']]

    admin.configuration.configgroup_manager:
        class: '%admin.configuration.configgroup_manager.class%'
        arguments:
            - '@service_container'
    admin.configuration.admin.configgroup:
        class: VinceT\AdminConfigurationBundle\Admin\ConfigGroupAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: AdminConfiguration, label: ConfigGroup, label_translator_strategy: sonata.admin.label.strategy.underscore }
        arguments:
            - null
            - VinceT\AdminConfigurationBundle\Entity\ConfigGroup
            - 'VinceTAdminConfigurationBundle:Admin/ConfigGroupAdmin'
        calls:
            - [setTranslationDomain, [VinceTAdminConfigurationBundleConfigGroup]]
            - [setModelManager, ['@admin.configuration.configgroup_manager']]
            - [setTemplate, [list, 'VinceTAdminConfigurationBundle:Configuration:list.html.twig']]

    admin.configuration.configvalue_manager:
        class: '%admin.configuration.configvalue_manager.class%'
        arguments:
            - '@service_container'
    admin.configuration.admin.configvalue:
        class: VinceT\AdminConfigurationBundle\Admin\ConfigValueAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: AdminConfiguration, label: ConfigValue, label_translator_strategy: sonata.admin.label.strategy.underscore }
        arguments:
            - null
            - VinceT\AdminConfigurationBundle\Entity\ConfigValue
            - 'VinceTAdminConfigurationBundle:Admin/ConfigValueAdmin'
        calls:
            - [setTranslationDomain, [VinceTAdminConfigurationBundleConfigValue]]
            - [setModelManager, ['@admin.configuration.configvalue_manager']]
            - [setTemplate, [list, 'VinceTAdminConfigurationBundle:Configuration:list.html.twig']]

    admin.configuration.configtype_manager:
        class: '%admin.configuration.configtype_manager.class%'
        arguments:
            - '@service_container'
    admin.configuration.admin.configtype:
        class: VinceT\AdminConfigurationBundle\Admin\ConfigTypeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: AdminConfiguration, label: ConfigType, label_translator_strategy: sonata.admin.label.strategy.underscore }
        arguments:
            - null
            - VinceT\AdminConfigurationBundle\Entity\ConfigType
            - 'VinceTAdminConfigurationBundle:Admin/ConfigTypeAdmin'
        calls:
            - [setTranslationDomain, [VinceTAdminConfigurationBundleConfigType]]
            - [setModelManager, ['@admin.configuration.configtype_manager']]
            - [setTemplate, [list, 'VinceTAdminConfigurationBundle:Configuration:list.html.twig']]

    vince_t.admin.configuration.validator.name:
        class: VinceT\AdminConfigurationBundle\Validator\Constraints\IsValidNameValidator
        tags:
            - { name: validator.constraint_validator, alias: vince_t_admin_name_validator }
        calls:
            - [setContainer, ['@service_container']]
    vince_t.admin.configuration.validator.configsection:
        class: VinceT\AdminConfigurationBundle\Validator\Constraints\ConfigSectionValidator
        tags:
            - { name: validator.constraint_validator, alias: vince_t_admin_configsection_validator }
        calls:
            - [setContainer, ['@service_container']]
    vince_t.admin.configuration.validator.configgroup:
        class: VinceT\AdminConfigurationBundle\Validator\Constraints\ConfigGroupValidator
        tags:
            - { name: validator.constraint_validator, alias: vince_t_admin_configgroup_validator }
        calls:
            - [setContainer, ['@service_container']]
    vince_t.admin.configuration.validator.configvalue:
        class: VinceT\AdminConfigurationBundle\Validator\Constraints\ConfigValueValidator
        tags:
            - { name: validator.constraint_validator, alias: vince_t_admin_configvalue_validator }
        calls:
            - [setContainer, ['@service_container']]

    admin.configuration.configbuilder:
        class: %admin.configuration.configbuilder.class%
        arguments:
            - @service_container
    admin.configuration.pool:
        class: %admin.configuration.pool.class%
        arguments:
            - @service_container