<?php
/**
 * This file is part of VinceTAdminConfigurationBundle for Symfony2
 *
 * @category VinceT
 * @package  VinceTAdminConfigurationBundle
 * @author   Vincent Touzet <vincent.touzet@gmail.com>
 * @license  MIT License view the LICENSE file that was distributed with this source code.
 * @link     https://github.com/vincenttouzet/AdminConfigurationBundle
 */

namespace VinceT\AdminConfigurationBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ConfigValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 * 
 * @category VinceT
 * @package  VinceTAdminConfigurationBundle
 * @author   Vincent Touzet <vincent.touzet@gmail.com>
 * @license  MIT License view the LICENSE file that was distributed with this source code.
 * @link     https://github.com/vincenttouzet/AdminConfigurationBundle
 */
class ConfigValueRepository extends EntityRepository
{
    /**
     * Find a ConfigValue by path
     *     <section_name>:<group_name>:<value_name>
     *
     * @param string $path Path of the value
     *
     * @return VinceT\AdminConfigurationBundle\Entity\ConfigGroup|null
     */
    public function findOneByPath($path)
    {
        list($sname, $gname, $vname) = explode(':', $path);
        return $this->findOneBySectionGroupAndValueName($sname, $gname, $vname);
    }
    /**
     * Find a ConfigGroup by the section and group name
     *
     * @param string $sectionName [description]
     * @param string $groupName   [description]
     * @param string $valueName   [description]
     *
     * @return VinceT\AdminConfigurationBundle\Entity\ConfigGroup|null
     */
    public function findOneBySectionGroupAndValueName($sectionName, $groupName, $valueName)
    {
        $query = $this->createQueryBuilder('v')
            ->select('v', 'g', 's')
            ->innerJoin('v.configGroup', 'g')
            ->innerJoin('g.configSection', 's')
            ->where('s.name = :sname')
            ->andWhere('g.name = :gname')
            ->andWhere('v.name = :vname')
            ->setParameter('sname', $sectionName)
            ->setParameter('gname', $groupName)
            ->setParameter('vname', $valueName)
            ->setMaxResults('1')
            ->getQuery();
        $result = $query->getResult();
        $res = null;
        if ( isset($result[0]) ) {
            $res = $result[0];
        }
        return $res;
    }

    /**
     * Find ConfigValue by the config group id
     *
     * @param Integer $id ConfigGroup id
     *
     * @return array
     */
    public function findByConfigGroupId($id)
    {
        $query = $this->createQueryBuilder('v')
            ->innerJoin('v.configType', 't')
            ->where('v.configGroup = :gid')
            ->setParameter('gid', $id)
            ->orderBy('v.position', 'ASC')
            ->getQuery();
        $result = $query->getResult();
        return $result;
    }
}
