<?php
/**
 * This file is part of VinceTAdminConfigurationBundle for Symfony2
 *
 * @category VinceT
 * @package  VinceTAdminConfigurationBundle
 * @author   Vincent Touzet <vincent.touzet@gmail.com>
 * @license  MIT License view the LICENSE file that was distributed with this source code.
 * @link     https://github.com/vincenttouzet/AdminConfigurationBundle
 */

namespace VinceT\AdminConfigurationBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ConfigGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 * 
 * @category VinceT
 * @package  VinceTAdminConfigurationBundle
 * @author   Vincent Touzet <vincent.touzet@gmail.com>
 * @license  MIT License view the LICENSE file that was distributed with this source code.
 * @link     https://github.com/vincenttouzet/AdminConfigurationBundle
 */
class ConfigGroupRepository extends EntityRepository
{
    /**
     * Find a ConfigGroup by the section and group name
     *
     * @param string $sectionName [description]
     * @param string $groupName   [description]
     *
     * @return VinceT\AdminConfigurationBundle\Entity\ConfigGroup|null
     */
    public function findOneBySectionAndGroupName($sectionName, $groupName)
    {
        $query = $this->createQueryBuilder('g')
            ->innerJoin('g.configSection', 's')
            ->where('s.name = :sname')
            ->andWhere('g.name = :gname')
            ->setParameter('sname', $sectionName)
            ->setParameter('gname', $groupName)
            ->setMaxResults('1')
            ->getQuery();
        $result = $query->getResult();
        $res = null;
        if ( isset($result[0]) ) {
            $res = $result[0];
        }
        return $res;
    }

    /**
     * Find ConfigGroup by the config section id
     *
     * @param Integer $id ConfigGroup id
     *
     * @return array
     */
    public function findByConfigGroupId($id)
    {
        $query = $this->createQueryBuilder('g')
            ->where('g.configSection = :sid')
            ->setParameter('sid', $id)
            ->orderBy('g.position', 'ASC')
            ->getQuery();
        $result = $query->getResult();
        return $result;
    }

}
